name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          preCommands: |
            echo "*** setting up configurations ***"
            echo "*** checking DB ***"
            wrangler kv:namespace list > all_ids
            cat all_ids
            grep -Po '(?<=id\"\:\")[^\}\{]*(?=\",\"title\"\:\"dentist\-bot\-DENTIST)' all_ids > wanted_id
            cat wanted_id
            wholetxt=$(cat wanted_id)
            if [ -z "${checkk}" ]; then echo "*** DB not added... Adding DB ***" && wrangler kv:namespace create DENTIST_TELEGRAM_BOT > file_temp && grep -Po '(?<=id\s=\s\").*(?=\")' file_temp >> temp_cmd && cat temp_cmd && wholetxt=$(cat temp_cmd); else echo "*** DB exists ***"; fi
            echo $wholetxt
            sed -i "s|id_here|$wholetxt|g" wrangler.toml
            cat wrangler.toml
          postCommands: |
            wrangler kv:key put --binding='DENTIST_TELEGRAM_BOT' 'webhook_url' 'no_setup'
            echo "*** All Done ***"