name: Deploy

on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        env:
          USER: root
        with:
          apiToken: ${{ secrets.CF_CLIENT_API_TOKEN }}
          preCommands: |
			wrangler config
            echo "*** setting up configurations ***"
            echo "*** checking DB ***"
            wrangler kv:namespace list > all_ids
            wholetxt=$(cat all_ids)
            echo 'wholetext' && echo $wholetxt
            if [[ $wholetxt != *"DENTIST_TELEGRAM_BOT"* ]]; then echo "*** DB not added... Adding DB ***" && wrangler kv:namespace create DENTIST_TELEGRAM_BOT > file_temp && grep -Po '(?<=id\s=\s\").*(?=\")' file_temp >> temp_cmd && cat temp_cmd && wholetxt=$(cat temp_cmd); else echo "*** DB exists ***" && grep -Po '(?<=id\"\:\")[^\}\{]*(?=\",\"title\"\:\"dentist\-bot\-DENTIST)' all_ids > txtt && wholetxt=$(cat txtt); fi
            echo $wholetxt
            sed -i "s|id_here|$wholetxt|g" wrangler.toml
            cat wrangler.toml
          postCommands: |
            wrangler kv:key put --binding='DENTIST_TELEGRAM_BOT' 'webhook_url' 'no_setup'
            echo "*** All Done ***"
